---
- hosts: all
  become: true
  tasks:
    - name: Install python via pacman
      package:
        name: python
        state: present

    - name: Install vim
      package:
        name: vim
        state: present

    - name: Install 7zip
      package: name=7zip state=present

    - name: Ensure chrony is installed
      package: 
        name: chrony
        state: present

    - name: Ensure chrony is running
      service:
        name: chronyd
        state: started
        enabled: yes
